### ISSUE TITLE
Not clear how to install

### ISSUE THREAD

**Issue by sdudnic** [samesies/barber-jekyll#32]
I am newbie in GitHubPages, so I installed my repository, and by default is the minima theme.
Now, how to switch it to the barber theme? I downlaoded a zip file, what should I do with it?

The readme is not clear on this subject: 

> Run `bundle install` on your command line after downloading or cloning the theme. 

How do you imagine bundle install is linked with a downloaded zip file in the downloads folder??

**Comment by thomasvaeth** [comment]
You need to unzip the folder and change into that directory. I don't think these directions should be included in my theme because it's not unique. I would suggest going to Codecademy to learn how to use the [command line](https://www.codecademy.com/learn/learn-the-command-line) and [git](https://www.codecademy.com/learn/learn-git).

**Comment by sdudnic** [comment]
I have no problem with how to use the command line or git, but what I said that there is no very clear instructions in your readme. "unzip the folder and change to the folder, then launch the command" are not really evident. What you say is "download or clone, then arbitrary launch somewhere the bundle install"...
